[package]
name = "arith-parser"
version = "0.1.0"
authors = ["chansuke <chansuke@georepublic.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0.26"

[[bin]]
path = "src/main.rs"
name = "arithparser"

