[package]
name = "arith-parser"
version = "0.1.0"
authors = ["chansuke <chansuke@georepublic.de>"]
edition = "2018"

[dependencies]
anyhow = "1.0.41"
thiserror = "1.0.26"
structopt = "0.3.17"
rustyline = "8.2.0"

[[bin]]
bench = false
path = "src/main.rs"
name = "arithparser"

